# Generated by Django 4.1.7 on 2023-03-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_desc", models.CharField(max_length=50)),
                (
                    "image_link",
                    models.ImageField(
                        blank=True,
                        default="profile.png",
                        null=True,
                        upload_to="images/",
                    ),
                ),
            ],
        ),
    ]
