# Generated by Django 4.2 on 2023-04-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_images_caption_images_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_link',
            new_name='photo',
        ),
    ]
