# Generated by Django 4.2 on 2023-04-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_rename_image_link_images_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(default='profile.png', upload_to='images'),
        ),
    ]
